### ISSUE TITLE
Norconex http Collector won't start with jef monitor running

### ISSUE THREAD

**Issue by murdock71** [Norconex/jef-monitor#5] opened 2017-03-06 16:33 UTC
Whenever I leave jef monitor running my collector won't start.

The error I receive says that the file is locked by another process. As soon as I stop jef monitor everything works as expected and I can restart the monitor once the collection has begun.

Is this expected behavior? Is there a way to allow the monitor to keep running while still allowing indexing to take place? Or do I have to start and stop the monitoring app each time?

Thank You

**Comment by essiembre** [comment] 2017-03-06 17:43
Which version of both are you using?  File locking was purposely introduced in the snapshot versions to solve other issues, but JEF monitor should be able to read the files without causing issues (else we'll fix).

**Comment by murdock71** [comment] 2017-03-06 17:55
The collector is 2.6.0 which I know was the stable version when I downloaded it. JEF monitor is 4.0.4, although looking at the release date of that becoming stable I wonder if I didn't get a snapshot version.

How can I tell for certain?

If I do indeed have the snapshot version I assume I can download the new one and overwrite everything but the config folder and it should just work?

Thank You

**Comment by essiembre** [comment] 2017-03-06 18:00
Usually when you run the collector, the first few lines should list the versions in use.   You can upgrade a release, but I would not just overwrite the files since you will have duplicates (e.g., same Jars, but different versions).  So maybe backup the lib folder and and replace it. For the collector, make sure to reinstall your committer libraries.

You can also install in a different location and just copy your configs over.

**Comment by essiembre** [comment] 2017-03-08 20:11
I think I was able to reproduce and fix the locking issue you experienced.  The latest snapshot version of both [HTTP Collector](https://www.norconex.com/collectors/collector-http/download) and [Filesystem Collector](https://www.norconex.com/collectors/collector-filesystem/download) as well as the latest [JEF Monitor snapshot](https://www.norconex.com/jef/monitor/download) release contain the fix.  You will need to update both your collector and JEF Monitor.

Please confirm.

**Comment by essiembre** [comment] 2017-04-25 22:59
The fix is in the stable 4.0.5 release.

**Closed by essiembre** 2017-04-25 22:59 UTC
Labels: bug, fixed/done
